  const List<String> MUSCLE_LIST = [
    'Todos',
    'Bíceps',
    'Tríceps',
    'Dorsal',
    'Peito',
    'Ombro',
    'Lombar',
    'Trapézio',
    'Antebraço',
    'Gluteo',
    'Quadríceps',
    'Posterior',
    'Panturrilha',
  ];